### ISSUE TITLE
Update README with Database/OAuth Key Setup Instructions

### ISSUE THREAD

**Issue by drew-beamer** [Yeti-Robotics/polar-edge-analytics#60]
# User story
As a developer, I want to know how to set up the database and give myself admin rights, so I can easily set up the project 

# Acceptance criteria

- [ ] Detailed instructions (can easily replicated process) on how to set up database, get Discord private keys, etc. are included in the README.

**Comment by Whitegabriella789** [comment]
I'd like to help with this documentation. I'm a bit new to GitHub, but I have taken courses on it. Is that ok? Out of curiosity, is this referring to how to set up a dev app through Discord and how to access the private keys and everything? Because I can definitely do that. As for the database setup, I imagine it's going to go through different software, or is it all referring to Discord?
